language: python
install:
  - pip install mkdocs-material
  - pip install mike
script:
  - mike install-extras
  - mike deploy
  - mkdocs build --verbose --clean --strict

jobs:
  include:
    - stage: build main
      script: mike deploy
    if: branch = main OR type = pull_request
    - stage: release docs
      if: branch =~ /release/
      script: mike deploy ${TRAVIS_BRANCH#'release/'} --push
