site_name: "Web3j"
site_description: "Documentation portal for the web3j Blockchain Library"
site_author: "Web3 Labs"
site_url: "https://web3j.io/"

repo_name: "web3j/web3j"
repo_url: "https://github.com/web3j/web3j"

# Copyright
copyright: "Copyright &copy; 2017-2019 Web3 Labs Ltd"

nav:
  - Quickstart: quickstart.md
  - Getting Started:
      - Project Build Configuration: getting_started/project_build_configuration.md
      - Deploy a Node Locally: getting_started/deploy_node_locally.md
      - Interacting with a Node: getting_started/interacting_with_node.md
      - Deploy and Interact with Smart Contracts: getting_started/deploy_interact_smart_contracts.md
      - Filters and Pub/Sub: getting_started/pub_sub.md
      - TLS over Websockets: getting_started/tls_websockets.md
      - Examples: getting_started/examples.md
  - Modules:
      - Web3j Internal Modules: modules/modules.md
      - Web3j OpenAPI: modules/web3j_openapi.md
      - Web3j Unit: modules/testing_with_web3j_unit.md
      - Web3j EVM: modules/web3j_evm.md
  - Transactions:
      - Ethereum Transactions: transactions/transactions.md
      - Obtaining Ether: transactions/obtaining_ether.md
      - Ethereum Test Networks: transactions/ethereum_testnets.md
      - Gas: transactions/gas.md
      - Transfer Eth: transactions/transfer_eth.md
      - Transction Mechanisms: transactions/transaction_mechanisms.md
      - Transction Nonce: transactions/transaction_nonce.md
      - Transction Types: transactions/transaction_types.md
      - Transctions and Smart Contracts : transactions/transactions_and_smart_contracts.md
      - Wallet Files: transactions/wallet_files.md
  - Privacy & Permissioning:
      - Besu Quickstart: privacy/besu_quickstart.md
      - Privacy with Hyperledger Besu: privacy/privacy_with_besu.md
      - Privacy Support in Web3j: privacy/privacy_support_web3j.md
  - Smart Contracts:
      - Smart Contract Overview: smart_contracts/smart_contracts.md
      - Getting Started with Solidity: smart_contracts/getting_started_solidity.md
      - Compiling Solidity source code: smart_contracts/compiling_solidity.md
      - Construction and Deployment: smart_contracts/construction_and_deployment.md
      - Interacting with Smart Contracts: smart_contracts/interacting_with_smart_contract.md
      - Contract Validity: smart_contracts/contract_validity.md
      - Application Binary Interface: smart_contracts/application_binary_interface.md
      - Contracts Supported by Web3j: smart_contracts/contracts_supported_by_web3j.md
      - Smart Contract Example: smart_contracts/smart_contract_examples.md
  - Advanced:
      - Recursive Length Prefix: advanced/recursive_length_prefix.md
      - Filters and Events: advanced/filters_and_events.md
      - Management Apis: advanced/management_apis.md
      - Ethereum Name Service: advanced/ethereum_name_service.md
  - Command Line Tools: https://docs.epirus.io/sdk/cli/
  - References:
      - Troubleshooting: references/troubleshooting.md
      - Projects using Web3j: references/projects_using_web3j.md
      - Companies using Web3j: references/companies_using_web3j.md
      - Developer Guide: references/developer_guide.md
      - Links and Useful Resources: references/links_and_useful_resources.md
      - Thanks and Credits: references/thanks_and_credits.md

      # Configuration
theme:
  name: "material"
  language: "en"
  logo: "img/logo.png"
  favicon: "img/favicon.ico"
  feature:
    tabs: true
  palette:
    primary: "white"
    accent: "deep-orange"


# Customization
extra:
  manifest: "manifest.webmanifest"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/web3j"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/web3labs"
    - icon: "fontawesome/brands/linkedin"
      link: "https://linkedin.com/in/web3labs"

extra_css:
  - "stylesheets/extra.css"


# Google Analytics
google_analytics:
  - 'UA-85710619-1'
  - 'auto'


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.details
  - toc:
      permalink: true
      toc_depth: 6

plugins:
  - search:
      lang: en
